name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ./kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Get commit hash
        run: echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}

      - name: Build backend image with cache for amd64
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          tags: ${{ secrets.REGISTRY_HOST }}/bunseki/backend:${{ env.SHA }}
          push: false
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache/backend
          cache-to: type=local,dest=/tmp/.buildx-cache/backend-new
          load: true

      - name: Push backend image
        run: |
          rm -rf /tmp/.buildx-cache/backend
          mv /tmp/.buildx-cache/backend-new /tmp/.buildx-cache/backend
          docker push ${{ secrets.REGISTRY_HOST }}/bunseki/backend:${{ env.SHA }}

      - name: Build frontend image with cache for amd64
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          tags: ${{ secrets.REGISTRY_HOST }}/bunseki/frontend:${{ env.SHA }}
          push: false
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache/frontend
          cache-to: type=local,dest=/tmp/.buildx-cache/frontend-new
          load: true

      - name: Push frontend image
        run: |
          rm -rf /tmp/.buildx-cache/frontend
          mv /tmp/.buildx-cache/frontend-new /tmp/.buildx-cache/frontend
          docker push ${{ secrets.REGISTRY_HOST }}/bunseki/frontend:${{ env.SHA }}

      - name: Set new images to kustomization.yaml
        run: |
          cd k8s/overlays/prod
          kustomize edit set image backend='${{ secrets.REGISTRY_HOST }}/bunseki/backend:${{ env.SHA }}'
          kustomize edit set image frontend='${{ secrets.REGISTRY_HOST }}/bunseki/frontend:${{ env.SHA }}'

      - name: Apply built kubernetes config
        run: |
          cd k8s/overlays/prod
          kustomize build | kubectl apply -f -
