name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ./kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          tags: ${{ secrets.REGISTRY_HOST }}/bunseki/backend:${{ github.sha }}
          push: true
          platforms: linux/amd64
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          tags: ${{ secrets.REGISTRY_HOST }}/bunseki/frontend:${{ github.sha }}
          push: true
          platforms: linux/amd64
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend

      - name: Deploy to Kubernetes
        run: |
          cd k8s/overlays/prod
          kustomize edit set image backend='${{ secrets.REGISTRY_HOST }}/bunseki/backend:${{ github.sha }}'
          kustomize edit set image frontend='${{ secrets.REGISTRY_HOST }}/bunseki/frontend:${{ github.sha }}'
          kustomize build | kubectl apply -f -
